# Generated by Django 5.1 on 2025-01-30 18:54

import django.core.validators
from django.db import migrations, models

import core.enums.course_enum
import core.enums.status_enum
import core.enums.type_course


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('surname', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course', models.CharField(blank=True, choices=core.enums.course_enum.CourseEnum.choices, max_length=10, null=True)),
                ('course_format', models.CharField(blank=True, max_length=15, null=True)),
                ('course_type', models.CharField(blank=True, choices=core.enums.type_course.CourseTypeEnum.choices, max_length=100, null=True)),
                ('sum', models.IntegerField(blank=True, null=True)),
                ('alreadyPaid', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('utm', models.CharField(blank=True, max_length=100, null=True)),
                ('msg', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=core.enums.status_enum.StatusEnum.choices, max_length=15, null=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-id'],
            },
        ),
    ]
