# Generated by Django 5.1 on 2025-03-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='group_name',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
